### ISSUE TITLE
i don't see any change

### ISSUE THREAD

**Issue by Dr-Bob-isTheBestDoctor** [cheyao/firefox-config#1]
fellow arch user here i had to use chatgpt to figure out the instructions but when they are in the profile directory and in chrome it doesn't change the appearance of firefox.

**Comment by cheyao** [comment]
Hey! Are you sure you are putting the profile in the default profile folder?

![image](https://github.com/user-attachments/assets/df8ed5d8-a8e3-405f-9aa1-daaf4b8776e4)

In the about:profiles pages you can see that only the first profile is the default one, so you go to the `/home/cyao/.mozilla/firefox/i2t5mtjj.default-release` folder and you run `git clone https://github.com/cheyao/firefox-config/ chrome`

BTW the instructions are alr written in the readme https://github.com/cheyao/firefox-config?tab=readme-ov-file#installation

**Comment by cheyao** [comment]
Oh and I forgot!
![image](https://github.com/user-attachments/assets/facc1346-8506-4eed-a5bb-3aae5845a595)
You must go to `about:config`  and set `toolkit.legacyUserProfileCustomizations.stylesheets` to true!

**Comment by Dr-Bob-isTheBestDoctor** [comment]
thanks i quess i was missing the toolkit.legacy thingy but it works now
